apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: lock-pvc-controller-manager
  name: lock-pvc-controller-manager-metrics-service
  namespace: lock-pvc-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: lock-pvc-controller-manager
