# permissions for end users to view lockpvcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lockpvc-viewer-role
rules:
- apiGroups:
  - lock.io
  resources:
  - lockpvcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lock.io
  resources:
  - lockpvcs/status
  verbs:
  - get
